### ISSUE TITLE
Missing development environment info

### ISSUE THREAD

**Issue by fazl** [AranNomante/BugTracker#12]
How about a brief recipe in the readme file to explain what I need to install on my machine in order to easily navigate and build the code ?

**Comment by AranNomante** [comment]
I have updated Readme file, can you please check it out and see if it's clear and helpful?

**Comment by fazl** [comment]
That's a great overview, I'll close the ticket.
By the way, if you're still working on a project and would like to make it easier for others to help you work on the code, you could add sections like 'Downloading' and 'Building' (this one could contain subsections like 'Installing required tools/software' <-- here you could put direct links to the downloads for the development tools, especially if there are free versions).

PS for a modern agile programming team, you would want to let any team member assign a ticket to themselves (this is the SCRUM approach, team members choose which ticket they want to work on, it improves the psychological ownership of tasks, and motivation, and also tends to lead to efficient work, because a team member will generally prefer a task that s/he knows s/he can implement, over ones that are likely to be too difficult/slow/tricky).
